// This file is generated by kconfig_compiler from sitesettings.kcfg.
// All changes you do to this file will be lost.

#include "sitesettings.h"

SiteSettings::SiteSettings(const QString &number)
  : KConfigSkeleton( QString::fromLatin1( "protoeditorrc" ) )
  , mParamnumber(number)
{
  setCurrentGroup( QString::fromLatin1( "Site_%1" ).arg( mParamnumber ) );

  KConfigSkeleton::ItemString  *itemName;
  itemName = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "Name" ), mName );
  addItem( itemName, QString::fromLatin1( "Name" ) );
  KConfigSkeleton::ItemString  *itemUrl;
  itemUrl = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "URL" ), mUrl );
  addItem( itemUrl, QString::fromLatin1( "URL" ) );
  
/*  KConfigSkeleton::ItemInt  *itemPort;
  itemPort = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "Port" ), mPort, 80 );
  addItem( itemPort, QString::fromLatin1( "Port" ) );*/
  KConfigSkeleton::ItemPath  *itemLocalBaseDir;
  itemLocalBaseDir = new KConfigSkeleton::ItemPath( currentGroup(), QString::fromLatin1( "LocalBaseDir" ), mLocalBaseDir );
  addItem( itemLocalBaseDir, QString::fromLatin1( "LocalBaseDir" ) );

  KConfigSkeleton::ItemPath  *itemRemoteBaseDir;
  itemRemoteBaseDir = new KConfigSkeleton::ItemPath( currentGroup(), QString::fromLatin1( "RemoteBaseDir" ), mRemoteBaseDir );
  addItem( itemRemoteBaseDir, QString::fromLatin1( "RemoteBaseDir" ) );

  KConfigSkeleton::ItemPath  *itemDefaultFile;
  itemDefaultFile = new KConfigSkeleton::ItemPath( currentGroup(), QString::fromLatin1( "DefaultFile" ), mDefaultFile);
  addItem( itemDefaultFile, QString::fromLatin1( "DefaultFile" ) );
  
  KConfigSkeleton::ItemBool  *itemMatchFileInLowerCase;
  itemMatchFileInLowerCase = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "MatchFileInLowerCase" ), mMatchFileInLowerCase, false );
  addItem( itemMatchFileInLowerCase, QString::fromLatin1( "MatchFileInLowerCase" ) );

  KConfigSkeleton::ItemString  *itemDebuggerClient;
  itemDebuggerClient = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "DebuggerClient" ), mDebuggerClient, "DBG" );
  addItem( itemDebuggerClient, QString::fromLatin1( "DebuggerClient" ) );

  readConfig();
}


void SiteSettings::load(const QString& name, const QString& url,/* int port,*/
     const QString& remoteBaseDir, const QString& localBaseDir,
     const QString& defaultFile, bool matchFileInLowerCase,
     const QString& debuggerClient)
{
  mName = name;
  mUrl = url;
//   mPort = port;
  mRemoteBaseDir = remoteBaseDir;
  mLocalBaseDir = localBaseDir;
  mMatchFileInLowerCase = matchFileInLowerCase;
  mDebuggerClient = debuggerClient;
  mDefaultFile = defaultFile;
}

SiteSettings::~SiteSettings()
{
}

