// This file is generated by kconfig_compiler from dbgsettings.kcfg.
// All changes you do to this file will be lost.
#ifndef XDSETTINGS_H
#define XDSETTINGS_H

#include "debuggersettingsinterface.h"

class XDSettingsWidget;

class XDSettings : public DebuggerSettingsInterface
{
  public:
    XDSettings(const QString& name);
    ~XDSettings();

    int listenPort() const
    {
      return mListenPort;
    }

    bool enableJIT() const
    {
      return mEnableJIT;
    }

    virtual QString name() {
      return m_name;
    }

    virtual void loadValuesFromWidget();
    virtual DebuggerTab* widget();
  protected:

    // Xdebug
    int  mListenPort;
    bool mEnableJIT;

    QString m_name;
  private:
    XDSettingsWidget* m_widget;
};

#endif
