// This file is generated by kconfig_compiler from dbgsettings.kcfg.
// All changes you do to this file will be lost.

#include "dbgsettings.h"
#include "dbgsettingswidget.h"
#include "dbg_defs.h"

#include <qwidget.h>

DBGSettings::DBGSettings()
  : DebuggerSettingsInterface()
{
  m_widget = 0;
  
  setCurrentGroup( QString::fromLatin1( "DBG" ) );

  KConfigSkeleton::ItemBool  *itemBreakOnLoad;
  itemBreakOnLoad = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "BreakOnLoad" ), mBreakOnLoad, true );
  addItem( itemBreakOnLoad, QString::fromLatin1( "BreakOnLoad" ) );
  KConfigSkeleton::ItemBool  *itemSendErrors;
  itemSendErrors = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "SendErrors" ), mSendErrors, true );
  addItem( itemSendErrors, QString::fromLatin1( "SendErrors" ) );
  KConfigSkeleton::ItemBool  *itemSendLogs;
  itemSendLogs = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "SendLogs" ), mSendLogs, true );
  addItem( itemSendLogs, QString::fromLatin1( "SendLogs" ) );
  KConfigSkeleton::ItemBool  *itemSendOutput;
  itemSendOutput = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "SendOutput" ), mSendOutput, true );
  addItem( itemSendOutput, QString::fromLatin1( "SendOutput" ) );
  KConfigSkeleton::ItemBool  *itemSendDetailedOutput;
  itemSendDetailedOutput = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "SendDetailedOutput" ), mSendDetailedOutput, true );
  addItem( itemSendDetailedOutput, QString::fromLatin1( "SendDetailedOutput" ) );
  KConfigSkeleton::ItemInt  *itemListenPort;
  itemListenPort = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "ListenPort" ), mListenPort, DBG_DEFAULT_PORT );
  addItem( itemListenPort, QString::fromLatin1( "ListenPort" ) );

  KConfigSkeleton::ItemBool  *itemEnableJIT;
  itemEnableJIT = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "EnableJIT" ), mEnableJIT, true );
  addItem( itemEnableJIT, QString::fromLatin1( "EnableJIT" ) );

  readConfig();
}

DBGSettings::~DBGSettings()
{
}

void DBGSettings::loadValuesFromWidget()
{
  mBreakOnLoad = m_widget->breakOnLoad();
  mEnableJIT   = m_widget->enableJIT();
  mListenPort  = m_widget->listenPort();
  mSendDetailedOutput = m_widget->sendDetailedOutput();
  mSendErrors = m_widget->sendErrors();
  mSendLogs = m_widget->sendLogs();
  mSendOutput = m_widget->sendOutput();
}

DebuggerTab* DBGSettings::widget()
{
  if(!m_widget) {
    m_widget = new DBGSettingsWidget(this);
  }
  return m_widget;
}
