// This file is generated by kconfig_compiler from dbgsettings.kcfg.
// All changes you do to this file will be lost.

#include "xdsettings.h"
#include "xdsettingswidget.h"
#include "xd_defs.h"

#include <qwidget.h>

XDSettings::XDSettings(const QString& name)
  : DebuggerSettingsInterface(), m_name(name)
{
  m_widget = 0;
  
  setCurrentGroup( QString::fromLatin1( m_name ) );

  KConfigSkeleton::ItemInt  *itemListenPort;
  itemListenPort = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "ListenPort" ), mListenPort, XD_DEFAULT_PORT );
  addItem( itemListenPort, QString::fromLatin1( "ListenPort" ) );

  KConfigSkeleton::ItemBool  *itemEnableJIT;
  itemEnableJIT = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "EnableJIT" ), mEnableJIT, true );
  addItem( itemEnableJIT, QString::fromLatin1( "EnableJIT" ) );

  readConfig();
}

XDSettings::~XDSettings()
{
}

void XDSettings::loadValuesFromWidget()
{
  mEnableJIT   = m_widget->enableJIT();
  mListenPort  = m_widget->listenPort();
}

DebuggerTab* XDSettings::widget()
{
  if(!m_widget) {
    m_widget = new XDSettingsWidget(this);
  }
  return m_widget;
}
