// This file is generated by kconfig_compiler from extoutputsettings.kcfg.
// All changes you do to this file will be lost.

#include "extoutputsettings.h"

ExtOutputSettings::ExtOutputSettings(  )
  : KConfigSkeleton( QString::fromLatin1( "protoeditorrc" ) )
{
  setCurrentGroup( QString::fromLatin1( "ExternalOutput" ) );

  KConfigSkeleton::ItemBool  *itemUseExternalBrowser;
  itemUseExternalBrowser = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "UseExternalBrowser" ), mUseExternalBrowser, false );
  addItem( itemUseExternalBrowser, QString::fromLatin1( "UseExternalBrowser" ) );
  QValueList<KConfigSkeleton::ItemEnum::Choice> valuesBrowser;
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QString::fromLatin1( "Konqueror" );
    valuesBrowser.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QString::fromLatin1( "Mozilla" );
    valuesBrowser.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QString::fromLatin1( "Firefox" );
    valuesBrowser.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QString::fromLatin1( "Opera" );
    valuesBrowser.append( choice );
  }
  KConfigSkeleton::ItemEnum  *itemBrowser;
  itemBrowser = new KConfigSkeleton::ItemEnum( currentGroup(), QString::fromLatin1( "Browser" ), mBrowser, valuesBrowser, EnumBrowser::Konqueror );
  addItem( itemBrowser, QString::fromLatin1( "Browser" ) );

  readConfig();
}

ExtOutputSettings::~ExtOutputSettings()
{
}

