// This file is generated by kconfig_compiler from extoutputsettings.kcfg.
// All changes you do to this file will be lost.
#ifndef EXTOUTPUTSETTINGS_H
#define EXTOUTPUTSETTINGS_H

#include <kconfigskeleton.h>

class ExtOutputSettings : public KConfigSkeleton
{
  public:
    class EnumBrowser
    {
      public:
      enum { Konqueror, Mozilla, Firefox, Opera, COUNT };
    };

    ExtOutputSettings( );
    ~ExtOutputSettings();

    void setUseExternalBrowser(bool value)
    {
      mUseExternalBrowser = value;
    }

    bool useExternalBrowser() const
    {
      return mUseExternalBrowser;
    }

    void setBrowser(int value)
    {
      mBrowser = value;
    }

    int browser() const
    {
      return mBrowser;
    }

  protected:

    // ExternalOutput
    bool mUseExternalBrowser;
    int mBrowser;

  private:
};

#endif
